CREATE TABLE orders.USER_HDR(USER_ID BIGINT NOT NULL PRIMARY KEY DEFAULT orders.gen_custom_id(),
USER_EMP_ID VARCHAR(25) NOT NULL, 
USER_NAME VARCHAR(255) NOT NULL,
USER_PSW TEXT	NOT NULL,
USER_FNAME VARCHAR(125) NOT NULL,
USER_LNAME VARCHAR(125) NOT NULL,
USER_STATUS	SMALLINT     NOT NULL DEFAULT 1,
CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT (NOW() AT TIME ZONE 'UTC'),		
CREATED_BY bigint NOT NULL,
MODIFIED_AT	TIMESTAMP WITH TIME ZONE DEFAULT ('now'::timestamp AT TIME ZONE 'UTC'), -- ADD NOW() with UTC timezone as Default Value
MODIFIED_BY	bigint
);

CREATE FUNCTION update_modified_at_column() RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
	NEW.MODIFIED_AT = (NOW() AT TIME ZONE 'UTC');
	RETURN NEW;
END;
$$;


CREATE TRIGGER user_hdr_updated_at_modtime BEFORE UPDATE ON USER_HDR
FOR EACH ROW EXECUTE PROCEDURE update_modified_at_column();

